#pragma once
#include <cstdint>

enum e_skin_config_t : short
{
    CONFIG_DEAGLE,
    CONFIG_DUAL_BERETTAS,
    CONFIG_FIVE_SEVEN,
    CONFIG_GLOCK,
    CONFIG_AK47,
    CONFIG_AUG,
    CONFIG_AWP,
    CONFIG_FAMAS,
    CONFIG_G3SG1,
    CONFIG_GALIL,
    CONFIG_M249,
    CONFIG_M4A4,
    CONFIG_MAC10,
    CONFIG_P90,
    CONFIG_UMP,
    CONFIG_MP5SD,
    CONFIG_XM1024,
    CONFIG_BIZON,
    CONFIG_MAG7,
    CONFIG_NEGEV,
    CONFIG_SAWEDOFF,
    CONFIG_TEC9,
    CONFIG_TASER,
    CONFIG_HKP2000,
    CONFIG_MP7,
    CONFIG_MP9,
    CONFIG_NOVA,
    CONFIG_P250,
    CONFIG_SCAR20,
    CONFIG_SG553,
    CONFIG_SSG08,
    CONFIG_M4A1_S,
    CONFIG_USP_S,
    CONFIG_CZ75,
    CONFIG_REVOLVER,
    CONFIG_BAYONET,
    CONFIG_KNIFECSS,
    CONFIG_KNIFEFLIP,
    CONFIG_KNIFEGUT,
    CONFIG_KNIFEKARAMBIT,
    CONFIG_KNIFEM9BAYONET,
    CONFIG_KNIFETACTICAL,
    CONFIG_KNIFEFALCHION,
    CONFIG_KNIFESURVIVALBOWIE,
    CONFIG_KNIFEBUTTERFLY,
    CONFIG_KNIFEPUSH,
    CONFIG_KNIFECORD,
    CONFIG_KNIFECANIS,
    CONFIG_KNIFEURSUS,
    CONFIG_KNIFEGYPSYJACKKNIFE,
    CONFIG_KNIFEOUTDOOR,
    CONFIG_KNIFESTILETTO,
    CONFIG_KNIFEWIDOWMAKER,
    CONFIG_KNIFESKELETON,
    CONFIG_KNIFEKUKRI,

    CONFIG_UNKNOWN = 0xFFFFFFFFFF,
};

enum e_glove_config_t : short
{
    CONFIG_GLOVE_BLOODHOUND,
    CONFIG_GLOVE_SPORT,
    CONFIG_GLOVE_DRIVER,
    CONFIG_GLOVE_HAND,
    CONFIG_GLOVE_MOTO,
    CONFIG_GLOVE_SPECIALIST,
    CONFIG_GLOVE_HYDRA,
    CONFIG_GLOVE_BROKEN_FANG,

    CONFIG_GLOVE_UNKNOWN = 0xFFFFFFFFFF,
};

enum e_move_type : int
{
    movetype_none = 0,
    movetype_obsolete,
    movetype_walk,
    movetype_fly,
    movetype_flygravity,
    movetype_vphysics,
    movetype_push,
    movetype_noclip,
    movetype_observer,
    movetype_ladder,
    movetype_custom,
    movetype_last,
    movetype_max_bits = 5,
};

enum e_item_def_index_t : short
{
    WEAPON_DEAGLE = 1,
    WEAPON_DUAL_BERETTAS = 2,
    WEAPON_FIVE_SEVEN = 3,
    WEAPON_GLOCK = 4,
    WEAPON_AK47 = 7,
    WEAPON_AUG = 8,
    WEAPON_AWP = 9,
    WEAPON_FAMAS = 10,
    WEAPON_G3SG1 = 11,
    WEAPON_GALIL = 13,
    WEAPON_M249 = 14,
    WEAPON_M4A4 = 16,
    WEAPON_MAC10 = 17,
    WEAPON_P90 = 19,
    WEAPON_UMP = 24,
    WEAPON_MP5SD = 23,
    WEAPON_XM1024 = 25,
    WEAPON_BIZON = 26,
    WEAPON_MAG7 = 27,
    WEAPON_NEGEV = 28,
    WEAPON_SAWEDOFF = 29,
    WEAPON_TEC9 = 30,
    WEAPON_TASER = 31,
    WEAPON_HKP2000 = 32,
    WEAPON_MP7 = 33,
    WEAPON_MP9 = 34,
    WEAPON_NOVA = 35,
    WEAPON_P250 = 36,
    WEAPON_SCAR20 = 38,
    WEAPON_SG553 = 39,
    WEAPON_SSG08 = 40,
    WEAPON_FLASHBANG = 43,
    WEAPON_HEGRENADE = 44,
    WEAPON_SMOKE = 45,
    WEAPON_MOLOTOV = 46,
    WEAPON_DECOY = 47,
    WEAPON_INCDENDIARY = 48,
    WEAPON_HEALTHSHOT = 57,
    WEAPON_M4A1_S = 60,
    WEAPON_USP_S = 61,
    WEAPON_CZ75 = 63,
    WEAPON_REVOLVER = 64,
    WEAPON_BAYONET = 500,
    WEAPON_KNIFECSS = 503,
    WEAPON_KNIFEFLIP = 505,
    WEAPON_KNIFEGUT = 506,
    WEAPON_KNIFEKARAMBIT = 507,
    WEAPON_KNIFEM9BAYONET = 508,
    WEAPON_KNIFETACTICAL = 509,
    WEAPON_KNIFEFALCHION = 512,
    WEAPON_KNIFESURVIVALBOWIE = 514,
    WEAPON_KNIFEBUTTERFLY = 515,
    WEAPON_KNIFEPUSH = 516,
    WEAPON_KNIFECORD = 517,
    WEAPON_KNIFECANIS = 518,
    WEAPON_KNIFEURSUS = 519,
    WEAPON_KNIFEGYPSYJACKKNIFE = 520,
    WEAPON_KNIFEOUTDOOR = 521,
    WEAPON_KNIFESTILETTO = 522,
    WEAPON_KNIFEWIDOWMAKER = 523,
    WEAPON_KNIFESKELETON = 525,
    WEAPON_KNIFEKUKRI = 526,
};

inline short get_skin_config( short item_def )
{
    switch ( item_def )
    {
    case WEAPON_DEAGLE:
        return CONFIG_DEAGLE;
    case WEAPON_DUAL_BERETTAS:
        return CONFIG_DUAL_BERETTAS;
    case WEAPON_FIVE_SEVEN:
        return CONFIG_FIVE_SEVEN;
    case WEAPON_GLOCK:
        return CONFIG_GLOCK;
    case WEAPON_AK47:
        return CONFIG_AK47;
    case WEAPON_AUG:
        return CONFIG_AUG;
    case WEAPON_AWP:
        return CONFIG_AWP;
    case WEAPON_FAMAS:
        return CONFIG_FAMAS;
    case WEAPON_G3SG1:
        return CONFIG_G3SG1;
    case WEAPON_GALIL:
        return CONFIG_GALIL;
    case WEAPON_M249:
        return CONFIG_M249;
    case WEAPON_M4A4:
        return CONFIG_M4A4;
    case WEAPON_MAC10:
        return CONFIG_MAC10;
    case WEAPON_P90:
        return CONFIG_P90;
    case WEAPON_UMP:
        return CONFIG_UMP;
    case WEAPON_MP5SD:
        return CONFIG_MP5SD;
    case WEAPON_XM1024:
        return CONFIG_XM1024;
    case WEAPON_BIZON:
        return CONFIG_BIZON;
    case WEAPON_MAG7:
        return CONFIG_MAG7;
    case WEAPON_NEGEV:
        return CONFIG_NEGEV;
    case WEAPON_SAWEDOFF:
        return CONFIG_SAWEDOFF;
    case WEAPON_TEC9:
        return CONFIG_TEC9;
    case WEAPON_TASER:
        return CONFIG_TASER;
    case WEAPON_HKP2000:
        return CONFIG_HKP2000;
    case WEAPON_MP7:
        return CONFIG_MP7;
    case WEAPON_MP9:
        return CONFIG_MP9;
    case WEAPON_NOVA:
        return CONFIG_NOVA;
    case WEAPON_P250:
        return CONFIG_P250;
    case WEAPON_SCAR20:
        return CONFIG_SCAR20;
    case WEAPON_SG553:
        return CONFIG_SG553;
    case WEAPON_SSG08:
        return CONFIG_SSG08;
    case WEAPON_M4A1_S:
        return CONFIG_M4A1_S;
    case WEAPON_USP_S:
        return CONFIG_USP_S;
    case WEAPON_CZ75:
        return CONFIG_CZ75;
    case WEAPON_REVOLVER:
        return CONFIG_REVOLVER;
    case WEAPON_BAYONET:
        return CONFIG_BAYONET;
    case WEAPON_KNIFECSS:
        return CONFIG_KNIFECSS;
    case WEAPON_KNIFEFLIP:
        return CONFIG_KNIFEFLIP;
    case WEAPON_KNIFEGUT:
        return CONFIG_KNIFEGUT;
    case WEAPON_KNIFEKARAMBIT:
        return CONFIG_KNIFEKARAMBIT;
    case WEAPON_KNIFEM9BAYONET:
        return CONFIG_KNIFEM9BAYONET;
    case WEAPON_KNIFETACTICAL:
        return CONFIG_KNIFETACTICAL;
    case WEAPON_KNIFEFALCHION:
        return CONFIG_KNIFEFALCHION;
    case WEAPON_KNIFESURVIVALBOWIE:
        return CONFIG_KNIFESURVIVALBOWIE;
    case WEAPON_KNIFEBUTTERFLY:
        return CONFIG_KNIFEBUTTERFLY;
    case WEAPON_KNIFEPUSH:
        return CONFIG_KNIFEPUSH;
    case WEAPON_KNIFECORD:
        return CONFIG_KNIFECORD;
    case WEAPON_KNIFECANIS:
        return CONFIG_KNIFECANIS;
    case WEAPON_KNIFEURSUS:
        return CONFIG_KNIFEURSUS;
    case WEAPON_KNIFEGYPSYJACKKNIFE:
        return CONFIG_KNIFEGYPSYJACKKNIFE;
    case WEAPON_KNIFEOUTDOOR:
        return CONFIG_KNIFEOUTDOOR;
    case WEAPON_KNIFESTILETTO:
        return CONFIG_KNIFESTILETTO;
    case WEAPON_KNIFEWIDOWMAKER:
        return CONFIG_KNIFEWIDOWMAKER;
    case WEAPON_KNIFESKELETON:
        return CONFIG_KNIFESKELETON;
    case WEAPON_KNIFEKUKRI:
        return CONFIG_KNIFEKUKRI;
    }

    return CONFIG_UNKNOWN;
}

enum e_weapon_type : uint32_t
{
    WEAPONTYPE_KNIFE = 0x0,
    WEAPONTYPE_PISTOL = 0x1,
    WEAPONTYPE_SUBMACHINEGUN = 0x2,
    WEAPONTYPE_RIFLE = 0x3,
    WEAPONTYPE_SHOTGUN = 0x4,
    WEAPONTYPE_SNIPER_RIFLE = 0x5,
    WEAPONTYPE_MACHINEGUN = 0x6,
    WEAPONTYPE_C4 = 0x7,
    WEAPONTYPE_TASER = 0x8,
    WEAPONTYPE_GRENADE = 0x9,
    WEAPONTYPE_EQUIPMENT = 0xa,
    WEAPONTYPE_STACKABLEITEM = 0xb,
    WEAPONTYPE_FISTS = 0xc,
    WEAPONTYPE_BREACHCHARGE = 0xd,
    WEAPONTYPE_BUMPMINE = 0xe,
    WEAPONTYPE_TABLET = 0xf,
    WEAPONTYPE_MELEE = 0x10,
    WEAPONTYPE_SHIELD = 0x11,
    WEAPONTYPE_ZONE_REPULSOR = 0x12,
    WEAPONTYPE_UNKNOWN = 0x13,
};

inline short get_glove_config( short item_def )
{
    switch ( item_def )
    {
    case 5027:
        return CONFIG_GLOVE_BLOODHOUND;
    case 5030:
        return CONFIG_GLOVE_SPORT;
    case 5031:
        return CONFIG_GLOVE_DRIVER;
    case 5032:
        return CONFIG_GLOVE_HAND;
    case 5033:
        return CONFIG_GLOVE_MOTO;
    case 5034:
        return CONFIG_GLOVE_SPECIALIST;
    case 5035:
        return CONFIG_GLOVE_HYDRA;
    case 4725:
        return CONFIG_GLOVE_BROKEN_FANG;
    }

    return CONFIG_GLOVE_UNKNOWN;
}

enum e_aim_bot_hitboxes : unsigned int
{
    NONE = 0U,
    HEAD = ( 1 << 0 ),
    CHEST = ( 1 << 1 ),
    BODY = ( 1 << 2 ),
    LEGS = ( 1 << 3 ),
    FEET = ( 1 << 4 )
};

enum e_bones {
    BONE_SPINE = 0x1,
    BONE_SPINE1 = 0x2,
    BONE_SPINE2 = 0x3,
    BONE_SPINE3 = 0x4,
    BONE_NECK = 0x5,
    BONE_HEAD = 0x6,
    BONE_LEFT_UPPER_ARM = 0x8,
    BONE_LEFT_LOWER_ARM = 0x9,
    BONE_LEFT_ARM = 0xA,
    BONE_RIGHT_UPPER_ARM = 0xD,
    BONE_RIGHT_LOWER_ARM = 0xE,
    BONE_RIGHT_ARM = 0xF,
    BONE_LEFT_UPPER_LEG = 0x16,
    BONE_LEFT_LOWER_LEG = 0x17,
    BONE_LEFT_ANKLE = 0x18,
    BONE_RIGHT_UPPER_LEG = 0x19,
    BONE_RIGHT_LOWER_LEG = 0x1A,
    BONE_RIGHT_ANKLE = 0x1B,
};


//enum e_hitboxes {
//    HITBOX_PELVIS,
//    HITBOX_SPINE,
//    HITBOX_SPINE1,
//    HITBOX_SPINE2,
//    HITBOX_SPINE3,
//    HITBOX_NECK,
//    HITBOX_HEAD,
//    HITBOX_LEFT_CLAVICLE,
//    HITBOX_LEFT_UPPER_ARM,
//    HITBOX_LEFT_LOWER_ARM,
//    HITBOX_LEFT_HAND,
//    HITBOX_WEAPON_LEFT_HAND,
//    HITBOX_RIGHT_CLAVICLE,
//    HITBOX_RIGHT_UPPER_ARM,
//    HITBOX_RIGHT_LOWER_ARM,
//    HITBOX_RIGHT_HAND,
//    HITBOX_WEAPON_RIGHT_HAND,
//    HITBOX_JIGGLE_PRIMARY,
//    HITBOX_CHESTHIER_OFFSET,
//    HITBOX_WEAPONHIER_JNT
//};

enum e_hitboxes {
    /* HEAD */
    HITBOX_HEAD,
    HITBOX_NECK,
    /* BODY */
    HITBOX_PELVIS,
    HITBOX_STOMACH,
    HITBOX_CHEST,
    HITBOX_LOWER_CHEST,
    HITBOX_UPPER_CHEST,
    /* LEGS */
    HITBOX_RIGHT_THIGH,
    HITBOX_LEFT_THIGH,
    HITBOX_RIGHT_CALF,
    HITBOX_LEFT_CALF,
    HITBOX_RIGHT_FOOT,
    HITBOX_LEFT_FOOT,
    /* ARMS */
    HITBOX_RIGHT_HAND,
    HITBOX_LEFT_HAND,
    HITBOX_RIGHT_UPPER_ARM,
    HITBOX_RIGHT_FOREARM,
    HITBOX_LEFT_UPPER_ARM,
    HITBOX_LEFT_FOREARM,
    HITBOX_MAX
};

enum e_hit_group : uint32_t {
    HITGROUP_INVALID = -1,
    HITGROUP_GENERIC,
    HITGROUP_HEAD,
    HITGROUP_CHEST,
    HITGROUP_STOMACH,
    HITGROUP_LEFTARM,
    HITGROUP_RIGHTARM,
    HITGROUP_LEFTLEG,
    HITGROUP_RIGHTLEG,
    HITGROUP_NECK,
    HITGROUP_UNUSED,
    HITGROUP_GEAR,
    HITGROUP_SPECIAL,
    HITGROUP_COUNT,
};

enum contents_t {
    CONTENTS_EMPTY = 0,
    CONTENTS_SOLID = 0x1,
    CONTENTS_WINDOW = 0x2,
    CONTENTS_AUX = 0x4,
    CONTENTS_GRATE = 0x8,
    CONTENTS_SLIME = 0x10,
    CONTENTS_WATER = 0x20,
    CONTENTS_BLOCKLOS = 0x40,
    CONTENTS_OPAQUE = 0x80,
    CONTENTS_TESTFOGVOLUME = 0x100,
    CONTENTS_UNUSED = 0x200,
    CONTENTS_BLOCKLIGHT = 0x400,
    CONTENTS_TEAM1 = 0x800,
    CONTENTS_TEAM2 = 0x1000,
    CONTENTS_IGNORE_NODRAW_OPAQUE = 0x2000,
    CONTENTS_MOVEABLE = 0x4000,
    CONTENTS_AREAPORTAL = 0x8000,
    CONTENTS_PLAYERCLIP = 0x10000,
    CONTENTS_MONSTERCLIP = 0x20000,
    CONTENTS_CURRENT_0 = 0x40000,
    CONTENTS_CURRENT_90 = 0x80000,
    CONTENTS_CURRENT_180 = 0x100000,
    CONTENTS_CURRENT_270 = 0x200000,
    CONTENTS_CURRENT_UP = 0x400000,
    CONTENTS_CURRENT_DOWN = 0x800000,
    CONTENTS_ORIGIN = 0x1000000,
    CONTENTS_MONSTER = 0x2000000,
    CONTENTS_DEBRIS = 0x4000000,
    CONTENTS_DETAIL = 0x8000000,
    CONTENTS_TRANSLUCENT = 0x10000000,
    CONTENTS_LADDER = 0x20000000,
    CONTENTS_HITBOX = 0x40000000,
};


enum trace_masks_t {
    MASK_ALL = 0xFFFFFFFF,
    MASK_SOLID = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_MONSTER | CONTENTS_GRATE,
    MASK_PLAYERSOLID = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_PLAYERCLIP | CONTENTS_WINDOW | CONTENTS_MONSTER | CONTENTS_GRATE,
    MASK_NPCSOLID = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTERCLIP | CONTENTS_WINDOW | CONTENTS_MONSTER | CONTENTS_GRATE,
    MASK_NPCFLUID = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTERCLIP | CONTENTS_WINDOW | CONTENTS_MONSTER | CONTENTS_GRATE,
    MASK_WATER = CONTENTS_WATER | CONTENTS_MOVEABLE | CONTENTS_SLIME,
    MASK_OPAQUE = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_OPAQUE,
    MASK_OPAQUE_AND_NPCS = MASK_OPAQUE | CONTENTS_MONSTER,
    MASK_BLOCKLOS = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_BLOCKLOS,
    MASK_BLOCKLOS_AND_NPCS = MASK_BLOCKLOS | CONTENTS_MONSTER,
    MASK_VISIBLE = MASK_OPAQUE | CONTENTS_IGNORE_NODRAW_OPAQUE,
    MASK_VISIBLE_AND_NPCS = MASK_OPAQUE_AND_NPCS | CONTENTS_IGNORE_NODRAW_OPAQUE,
    MASK_SHOT = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTER | CONTENTS_WINDOW | CONTENTS_DEBRIS | CONTENTS_GRATE | CONTENTS_HITBOX,
    MASK_SHOT_BRUSHONLY = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_DEBRIS,
    MASK_SHOT_HULL = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_MONSTER | CONTENTS_WINDOW | CONTENTS_DEBRIS | CONTENTS_GRATE,
    MASK_SHOT_PORTAL = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_MONSTER,
    MASK_SOLID_BRUSHONLY = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_GRATE,
    MASK_PLAYERSOLID_BRUSHONLY = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_PLAYERCLIP | CONTENTS_GRATE,
    MASK_NPCSOLID_BRUSHONLY = CONTENTS_SOLID | CONTENTS_MOVEABLE | CONTENTS_WINDOW | CONTENTS_MONSTERCLIP | CONTENTS_GRATE,
    MASK_NPCWORLDSTATIC = CONTENTS_SOLID | CONTENTS_WINDOW | CONTENTS_MONSTERCLIP | CONTENTS_GRATE,
    MASK_NPCWORLDSTATIC_FLUID = CONTENTS_SOLID | CONTENTS_WINDOW | CONTENTS_MONSTERCLIP,
    MASK_SPLITAREPORTAL = CONTENTS_WATER | CONTENTS_SLIME,
    MASK_CURRENT = CONTENTS_CURRENT_0 | CONTENTS_CURRENT_90 | CONTENTS_CURRENT_180 | CONTENTS_CURRENT_270 | CONTENTS_CURRENT_UP | CONTENTS_CURRENT_DOWN,
    MASK_DEADSOLID = CONTENTS_SOLID | CONTENTS_PLAYERCLIP | CONTENTS_WINDOW | CONTENTS_GRATE,
};

enum e_bone_flags : uint32_t {
    FLAG_NO_BONE_FLAGS = 0x0,
    FLAG_BONEFLEXDRIVER = 0x4,
    FLAG_CLOTH = 0x8,
    FLAG_PHYSICS = 0x10,
    FLAG_ATTACHMENT = 0x20,
    FLAG_ANIMATION = 0x40,
    FLAG_MESH = 0x80,
    FLAG_HITBOX = 0x100,
    FLAG_BONE_USED_BY_VERTEX_LOD0 = 0x400,
    FLAG_BONE_USED_BY_VERTEX_LOD1 = 0x800,
    FLAG_BONE_USED_BY_VERTEX_LOD2 = 0x1000,
    FLAG_BONE_USED_BY_VERTEX_LOD3 = 0x2000,
    FLAG_BONE_USED_BY_VERTEX_LOD4 = 0x4000,
    FLAG_BONE_USED_BY_VERTEX_LOD5 = 0x8000,
    FLAG_BONE_USED_BY_VERTEX_LOD6 = 0x10000,
    FLAG_BONE_USED_BY_VERTEX_LOD7 = 0x20000,
    FLAG_BONE_MERGE_READ = 0x40000,
    FLAG_BONE_MERGE_WRITE = 0x80000,
    FLAG_ALL_BONE_FLAGS = 0xfffff,
    BLEND_PREALIGNED = 0x100000,
    FLAG_RIGIDLENGTH = 0x200000,
    FLAG_PROCEDURAL = 0x400000,
};